# Hourly scrapingg
name: nifty50scrape


# Controls when the action will run.
on:
 schedule:
    - cron: '*/5 * * * *'


jobs:
 autoscrape:
   # The type of runner that the job will run on
   runs-on: macos-13


   # Load repo and install R
   steps:
   - uses: actions/checkout@v2
   - uses: r-lib/actions/setup-r@v2


   # Set-up R
   - name: Install packages
     run: |
       R -e 'install.packages("tidyverse")'
       R -e 'install.packages("data.table")'
       R -e 'install.packages("rvest")'
  
   - name: Check out repository
     uses: actions/checkout@v3


   # Run R script
   - name: Scrape
     run: Rscript election_scrape.R


   - name: Scrape city results
     run: Rscript city_results.R


   - name: Scrape school district results
     run: Rscript school_results_new_layout.R


   - name: Scrape school board at large map
     run: Rscript SBatlargemapscrape.R
