# Hourly scraping
name: nifty50scrape

# Controls when the action will run.
on:
  push:
    branches:
      - main

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      # Set-up R and cache R packages
      - name: Install and Cache R packages
        run: |
          mkdir -p ${{ runner.workspace }}/Rpackages
          R_LIBS_USER="${{ runner.workspace }}/Rpackages"
          R -e 'install.packages("tidyverse", lib = Sys.getenv("R_LIBS_USER"), repos = "https://cran.rstudio.com/")'
          R -e 'install.packages("data.table", lib = Sys.getenv("R_LIBS_USER"), repos = "https://cran.rstudio.com/")'
          R -e 'install.packages("rvest", lib = Sys.getenv("R_LIBS_USER"), repos = "https://cran.rstudio.com/")'
        # Cache R packages
        - name: Cache R packages
          uses: actions/cache@v2
          with:
            path: ${{ runner.workspace }}/Rpackages
            key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
            restore-keys: |
              ${{ runner.os }}-R-

      # Run R script
      - name: Scrape
        run: Rscript election_scrape.R

      - name: Scrape city results
        run: Rscript city_results.R

      # Cache data folder
      - name: Cache data files
        uses: actions/cache@v2
        with:
          path: data
          key: data-${{ hashFiles('data/**') }}

      # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
