name: nifty50scrape

on:
  push:
    branches:
      - main

jobs:
  autoscrape:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("data.table")'
          R -e 'install.packages("rvest")'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run R script
        run: Rscript election_scrape.R
      - name: Scrape city results
        run: Rscript city_results.R
      - name: Scrape school district results
        run: Rscript school_results_new_layout.R
      - name: Scrape school board at large map
        run: Rscript SBatlargemapscrape.R
      - name: Scrape school board district 2
        run: Rscript SBD2mapscrape.R
      - name: Scrape school board district 3
        run: Rscript SBD3mapscrape.R
      - name: Scrape school referendum Q1
        run: Rscript SRQ1mapscrape.R
      - name: Scrape school referendum Q2
        run: Rscript SRQ2mapscrape.R
      - name: Scrape city at large for map
        run: Rscript city_atlarge_map.R
      - name: Scrape city district 1 for map
        run: Rscript city_district1_map.R
      - name: Scrape city district 3 for map
        run: Rscript city_district3_map.R
      - name: Scrape city district 4 for map
        run: Rscript city_district4_map.R
      - name: Scrape city district 5 for map
        run: Rscript city_district5_map.R
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

  repeat:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger the workflow
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'neutral' }}
        run: |
          echo "Repeating the workflow"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
